name: Build KDoc

on:
  push:
    branches: [master]

jobs:
  dokka:
    runs-on: ubuntu-latest

    steps:
      - name: Clone master branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
          submodules: "recursive"
          token: ${{ secrets.GITHUB_TOKEN}}
          path: "./EzXHelper"

      - name: Prepare Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('/*.gradle') }}-${{ hashFiles('/*.gradle.kts') }}
      - name: Set git identity
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Build KDoc
        run: |
          yes | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --licenses &> /dev/null
          cd ./EzXHelper
          ./gradlew :EzXHelper:dokkaHtml

      - name: Push to gh-pages
        if: success()
        run: |
          mkdir gh-pages
          cd EzXHelper
          cp ./EzXHelper/build/dokka/html/* ../gh-pages -rf
          git checkout gh-pages
          echo -e ".gradle\nEzXHelper/build" > .gitignore
          cp ../gh-pages . -rf
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "Auto commit at $(date)"
            git push origin gh-pages
          else
            echo "Skip push without change"
          fi
